const drivers = [
    { name: "Yevhenii PANCHENKO", team: "Mercedes", number: "22", country: "🇺🇦", points: 26, wins: 0, poles: 0, races: 4, dnf: 1, podiums: 0 },
    { name: "Maksym FILIPOV", team: "Mercedes", number: "52", country: "🇺🇦", points: 5, wins: 0, poles: 0, races: 6, dnf: 2, podiums: 0 },
    { name: "Nazar SHTEFANIUK", team: "Williams", number: "29", country: "🇺🇦", points: 35, wins: 1, poles: 0, races: 3, dnf: 0, podiums: 1 },
    { name: "Mykhailo ILLIUK", team: "Williams", number: "18", country: "🇺🇦", points: 11, wins: 0, poles: 0, races: 4, dnf: 1, podiums: 0 },
    { name: "Rostyslav PYLIAK", team: "Ferrari", number: "59", country: "🇺🇦", points: 21, wins: 0, poles: 0, races: 5, dnf: 2, podiums: 0 },
    { name: "Maksym MYKHLYK", team: "Ferrari", number: "27", country: "🇺🇦", points: 3, wins: 0, poles: 0, races: 4, dnf: 0, podiums: 0 },
    { name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", number: "69", country: "🇺🇦", points: 28, wins: 0, poles: 0, races: 6, dnf: 0, podiums: 0 },
    { name: "Olexandr KORZHOVSKYI", team: "Red Bull Racing", number: "06", country: "🇺🇦", points: 18, wins: 0, poles: 0, races: 1, dnf: 0, podiums: 1 },
    { name: "Yaroslav LOBODA", team: "Alpine", number: "10", country: "🇺🇦", points: 51, wins: 0, poles: 0, races: 6, dnf: 2, podiums: 2 },
    { name: "Yaroslav PANKRATOV", team: "Alpine", number: "15", country: "🇺🇦", points: 63, wins: 0, poles: 0, races: 6, dnf: 1, podiums: 5 },
    { name: "Yulian HULYK", team: "Aston Martin", number: "85", country: "🇺🇦", points: 92, wins: 4, poles: 5, races: 5, dnf: 0, podiums: 5 },
    { name: "Maks ZHUK", team: "Aston Martin", number: "03", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 1, dnf: 0, podiums: 0 },
    { name: "Dmytro SHOLOPKO", team: "Racing Bulls", number: "68", country: "🇺🇦", points: 7, wins: 0, poles: 0, races: 5, dnf: 1, podiums: 0 },
    { name: "Hlib BRATUS", team: "Haas F1 Team", number: "82", country: "🇺🇦", points: 19, wins: 0, poles: 0, races: 2, dnf: 0, podiums: 0 },
    { name: "Stanislav MARCHENKO", team: "Haas F1 Team", number: "87", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 1, dnf: 1, podiums: 0 },
    { name: "Oleh LIASHKO", team: "McLaren", number: "91", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 3, dnf: 3, podiums: 0 },
    { name: "Volodymyr SHAKULA", team: "Kick Sauber", number: "40", country: "🇺🇦", points: 61, wins: 0, poles: 0, races: 6, dnf: 0, podiums: 3 },
    { name: "Stanislav KRICHFALOVSKYI", team: "Kick Sauber", number: "24", country: "🇺🇦", points: 1, wins: 0, poles: 0, races: 4, dnf: 1, podiums: 0 },
    
    // Reserve Drivers
    { name: "Denys ZABARNYI", team: "Reserve", number: "64", country: "🇺🇦", points: 13, wins: 0, poles: 1, races: 0, dnf: 0, podiums: 0 },
    { name: "Denys ILCHUK", team: "Reserve", number: "05", country: "🇺🇦", points: 2, wins: 0, poles: 0, races: 2, dnf: 0, podiums: 0 },
    { name: "Viktor BEREZHNYI", team: "Reserve", number: "11", country: "🇺🇦", points: 3, wins: 0, poles: 0, races: 1, dnf: 0, podiums: 0 },
    { name: "Olexandr SAVIN", team: "Reserve", number: "88", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 1, dnf: 0, podiums: 0 },
    { name: "Maksym KYRYLCHUK", team: "Reserve", number: "99", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 1, dnf: 0, podiums: 0 },
    { name: "Roman KOVSH", team: "Reserve", number: "35", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 0, dnf: 0, podiums: 0 },
    { name: "Yevhen BARANOV", team: "Reserve", number: "42", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 0, dnf: 0, podiums: 0 },
    { name: "Serhii SOKHAN", team: "Reserve", number: "19", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 0, dnf: 0, podiums: 0 },
    { name: "Hlib HOLOVKOV", team: "Reserve", number: "95", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 0, dnf: 0, podiums: 0 },
    { name: "Artem VODOPIANOV", team: "Reserve", number: "46", country: "🇺🇦", points: 13, wins: 0, poles: 0, races: 3, dnf: 0, podiums: 0 },
    { name: "Illia KHUDAVSKYI", team: "Reserve", number: "55", country: "🇺🇦", points: 5, wins: 0, poles: 0, races: 2, dnf: 0, podiums: 0 },
    { name: "Klym YELISIEIEV", team: "Reserve", number: "09", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 1, dnf: 1, podiums: 0 },
    { name: "Dmytro POLIANSKYI", team: "Reserve", number: "32", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 1, dnf: 0, podiums: 0 },
    { name: "Olexandr LARIONOV", team: "Reserve", number: "16", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 3, dnf: 2, podiums: 0 },
    { name: "Igor DOVHAN", team: "Reserve", number: "07", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 1, dnf: 1, podiums: 0 },
    { name: "Bohdan VOSKOBIINYK", team: "Reserve", number: "14", country: "🇺🇦", points: 0, wins: 0, poles: 0, races: 2, dnf: 2, podiums: 0 },
    { name: "Vladyslav POROSHENKO", team: "Reserve", number: "65", country: "🇺🇦", points: 25, wins: 1, poles: 0, races: 3, dnf: 2, podiums: 0 }
];

const teams = [
    { 
        name: "Alpine", 
        drivers: ["Yaroslav LOBODA", "Yaroslav PANKRATOV"],
        points: 114, // Вкажіть актуальну суму очок
        wins: 0,
        podiums: 7
    },
    { 
        name: "Aston Martin", 
        drivers: ["Yulian HULYK", "Maks ZHUK"],
        points: 92,
        wins: 4,
        podiums: 5
    },
    { 
        name: "Williams", 
        drivers: ["Nazar SHTEFANIUK", "Mykhailo ILLIUK"],
        points: 64,
        wins: 1,
        podiums: 1
    },
    { 
        name: "Kick Sauber", 
        drivers: ["Volodymyr SHAKULA", "Stanislav KRICHFALOVSKYI"],
        points: 64,
        wins: 0,
        podiums: 3
    },
    { 
        name: "Ferrari", 
        drivers: ["Rostyslav PYLIAK", "Maksym MYKHLYK"],
        points: 24,
        wins: 0,
        podiums: 0
    },
    { 
        name: "Red Bull Racing", 
        drivers: ["Volodymyr MYKHALYUK", "Olexandr KORZHOVSKYI"],
        points: 28,
        wins: 0,
        podiums: 0
    },
    { 
        name: "Mercedes", 
        drivers: ["Yevhenii PANCHENKO", "Maksym FILIPOV"],
        points: 34,
        wins: 0,
        podiums: 0
    },
    { 
        name: "Racing Bulls", 
        drivers: ["Dmytro SHOLOPKO"],
        points: 19,
        wins: 0,
        podiums: 0
    },
    { 
        name: "McLaren", 
        drivers: ["Oleh LIASHKO"],
        points: 26,
        wins: 0,
        podiums: 0
    },
    { 
        name: "Haas F1 Team", 
        drivers: ["Hlib BRATUS", "Stanislav MARCHENKO"],
        points: 37,
        wins: 0,
        podiums: 0
    }
];

const calendar = [
    { round: 1, country: "Australia", flag: "🇦🇺", track: "Melbourne", date: "21 JUN", status: "Completed", hasSprint: false },
    { round: 2, country: "China", flag: "🇨🇳", track: "Shanghai", date: "28 JUN", status: "Completed", hasSprint: true },
    { round: 3, country: "Japan", flag: "🇯🇵", track: "Suzuka", date: "12 JUL", status: "Completed", hasSprint: false },
    { round: 4, country: "Monaco", flag: "🇲🇨", track: "Monte Carlo", date: "27 JUL", status: "Completed", hasSprint: false },
    { round: 5, country: "Great Britain", flag: "🇬🇧", track: "Silverstone", date: "31 JUL", status: "Completed", hasSprint: false },
    { round: 6, country: "Austria", flag: "🇦🇹", track: "Spielberg", date: "7 AUG", status: "Upcoming", hasSprint: false },
    { round: 7, country: "Italy", flag: "🇮🇹", track: "Monza", date: "14 AUG", status: "Upcoming", hasSprint: false },
    { round: 8, country: "Azerbaijan", flag: "🇦🇿", track: "Baku", date: "20-21 AUG", status: "Upcoming", hasSprint: true },
    { round: 9, country: "Brazil", flag: "🇧🇷", track: "São Paulo", date: "28 AUG", status: "Upcoming", hasSprint: false },
    { round: 10, country: "USA", flag: "🇺🇸", track: "Miami", date: "03-04 SEP", status: "Upcoming", hasSprint: true },
    { round: 11, country: "Qatar", flag: "🇶🇦", track: "Doha", date: "11 SEP", status: "Upcoming", hasSprint: false },
    { round: 12, country: "Abu Dhabi", flag: "🇦🇪", track: "Yas Island", date: "18 SEP", status: "Upcoming", hasSprint: false }
];

// Результати за сесіями
const raceResults = [
    {
        round: 1,
        country: "Australia",
        sessions: {
            qualifying: [
                { pos: 1, number: "64", name: "Denys ZABARNYI", team: "Racing Bulls", time: "1:15.718", gap: "LEADER" },
                { pos: 2, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "1:15.843", gap: "+0.125" },
                { pos: 3, number: "29", name: "Nazar SHTEFANIUK", team: "Williams", time: "1:16.230", gap: "+0.512" },
                { pos: 4, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "1:16.339", gap: "+0.621" },
                { pos: 5, number: "46", name: "Artem VODOPIANOV", team: "Reserve", time: "1:16.667", gap: "+0.959" },
                { pos: 6, number: "99", name: "Maksym KYRYLCHUK", team: "Reserve", time: "1:16.791", gap: "+1.073" },
                { pos: 7, number: "09", name: "Klym YELISIEIEV", team: "Reserve", time: "1:16.944", gap: "+1.226" },
                { pos: 8, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "1:17.152", gap: "+1.434" },
                { pos: 9, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "1:17.268", gap: "+1.550" },
                { pos: 10, number: "59", name: "Rostyslav PYLIAK", team: "Ferrari", time: "1:17.279", gap: "+1.561" },
                { pos: 11, number: "55", name: "Illia KHUDAVSKYI", team: "Reserve", time: "1:17.515", gap: "+1.797" },
                { pos: 12, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "1:17.541", gap: "+1.823" },
                { pos: 13, number: "88", name: "Olexandr SAVIN", team: "Reserve", time: "1:17.920", gap: "+2.202" },
                { pos: 14, number: "18", name: "Mykhailo ILLIUK", team: "Williams", time: "1:18.111", gap: "+2.393" },
                { pos: 15, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "1:18.764", gap: "+3.046" },
                { pos: 16, number: "32", name: "Dmytro POLIANSKYI", team: "Reserve", time: "1:19.838", gap: "+4.120" },
                { pos: 17, number: "24", name: "Stanislav KRICHFALOVSKYI", team: "Kick Sauber", time: "1:20.947", gap: "+5.229" },
                { pos: 18, number: "16", name: "Olexandr LARIONOV", team: "Reserve", time: "DSQ", gap: "-" },
                { pos: 19, number: "14", name: "Bohdan VOSKOBIINYK", team: "Reserve", time: "DSQ", gap: "-" },
                { pos: 20, number: "07", name: "Igor DOVHAN", team: "Reserve", time: "DSQ", gap: "-" },
            ],
            race: [
                { pos: 1, number: "29", name: "Nazar SHTEFANIUK", team: "Williams", time: "01:27:18.183", gap: "LEADER", points: 25 },
                { pos: 2, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "+16.516s", gap: "-", points: 18 },
                { pos: 3, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "+28.985s", gap: "-", points: 15 },
                { pos: 4, number: "64", name: "Denys ZABARNYI", team: "Reserve", time: "+37.455s", gap: "-", points: 13 },
                { pos: 5, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "+49.633s", gap: "-", points: 10 },
                { pos: 6, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "+58.282s", gap: "-", points: 8 },
                { pos: 7, number: "46", name: "Artem VODOPIANOV", team: "Reserve", time: "+1:16.641", gap: "-", points: 6 },
                { pos: 8, number: "59", name: "Rostyslav PYLIAK", team: "Ferrari", time: "+1 lap", gap: "-", points: 4 },
                { pos: 9, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "+1 lap", gap: "-", points: 2 },
                { pos: 10, number: "55", name: "Illia KHUDAVSKYI", team: "Reserve", time: "+1 lap", gap: "-", points: 1 },
                { pos: 11, number: "18", name: "Mykhailo ILLIUK", team: "Williams", time: "+1 lap", gap: "-", points: 0 },
                { pos: 12, number: "88", name: "Olexandr SAVIN", team: "Reserve", time: "+2 lap", gap: "-", points: 0 },
                { pos: 13, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "+2 lap", gap: "-", points: 0 },
                { pos: 14, number: "24", name: "Stanislav KRICHFALOVSKYI", team: "Kick Sauber", time: "+2 lap", gap: "-", points: 0 },
                { pos: 15, number: "32", name: "Dmytro POLIANSKYI", team: "Reserve", time: "+3 lap", gap: "-", points: 0 },
                { pos: 16, number: "16", name: "Olexandr LARIONOV", team: "Reserve", time: "DNF", gap: "-", points: 0 },
                { pos: 17, number: "09", name: "Klym YELISIEIEV", team: "Reserve", time: "DNF", gap: "-", points: 0 },
                { pos: 18, number: "99", name: "Maksym KYRYLCHUK", team: "Reserve", time: "DNF", gap: "-", points: 0 },
                { pos: 19, number: "07", name: "Igor DOVHAN", team: "Reserve", time: "DNF", gap: "-", points: 0 },
                { pos: 20, number: "14", name: "Bohdan VOSKOBIINYK", team: "Reserve", time: "DNF", gap: "-", points: 0 },

            ]
        }
    },
    {
        round: 2,
        country: "China",
        sessions: {
            sprintRace: [
                { pos: 1, number: "85", name: "Yulian HULYK", team: "Aston Martin", time: "Interval", gap: "-", points: 8 },
                { pos: 2, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "+24.684s", gap: "-", points: 7 },
                { pos: 3, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "+28.470s", gap: "-", points: 6 },
                { pos: 4, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "+40.161s", gap: "-", points: 5 },
                { pos: 5, number: "59", name: "Rostyslav PYLIAK", team: "Ferrari", time: "+40.297s", gap: "-", points: 4 },
                { pos: 6, number: "11", name: "Viktor BEREZNYI", team: "Reserve", time: "+41.047s", gap: "-", points: 3 },
                { pos: 7, number: "05", name: "Denys ILCHUK", team: "Reserve", time: "+1:14.952", gap: "-", points: 2 },
                { pos: 8, number: "46", name: "Artem VODOPIANOV", team: "Reserve", time: "+1:16.162", gap: "-", points: 1 },
                { pos: 9, number: "27", name: "Maksym MYKHLYK", team: "Ferrari", time: "+1:17.060", gap: "-", points: 0 },
                { pos: 10, number: "29", name: "Nazar SHTEFANIUK", team: "Williams", time: "+1:50.548", gap: "-", points: 0 },
                { pos: 11, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "+1:52.279", gap: "-", points: 0 },
                { pos: 12, number: "85", name: "Maks ZHUK", team: "Aston Martin", time: "+1:52.604", gap: "-", points: 0 },
                { pos: 13, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "+1:55.702", gap: "-", points: 0 },
                { pos: 14, number: "16", name: "Olexandr LARIONOV", team: "Reserve", time: "+2:15.065", gap: "-", points: 0 },
                { pos: 15, number: "68", name: "Dmytro SHOLOPKO", team: "Racing Bulls", time: "+ 2:31.203", gap: "-", points: 0 },
                { pos: 16, number: "55", name: "Illia KHUDAVSKYI", team: "Reserve", time: "DNS", gap: "-", points: 0 },
                { pos: 17, number: "18", name: "Mykhailo ILLIUK", team: "Williams", time: "DNS", gap: "-", points: 0 },
                { pos: 18, number: "64", name: "Denys ZABARNYI", team: "Reserve", time: "DNS", gap: "-", points: 0 },
                { pos: 19, number: "32", name: "Dmytro POLIANSKYI", team: "Reserve", time: "DNS", gap: "-", points: 0 },
                
            ],
            qualifying: [
                { pos: 1, number: "85", name: "Yulian HULYK", team: "Aston Martin", time: "1:46.107", gap: "LEADER" },
                { pos: 2, number: "06", name: "Olexandr KORZHOVSKYI", team: "Williams", time: "1:47.933", gap: "+1.826" },
                { pos: 3, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "1:48.204", gap: "+2.097" },
                { pos: 4, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "1:48.405", gap: "+2.298" },
                { pos: 5, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "1:48.420", gap: "+2.313" },
                { pos: 6, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "1:48.426", gap: "+2.319" },
                { pos: 7, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "1:48.652", gap: "+2.545" },
                { pos: 8, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "1:49.347", gap: "+3.240" },
                { pos: 9, number: "05", name: "Denys ILCHUK", team: "Kick Sauber", time: "1:53.093", gap: "+6.986" },
                { pos: 10, number: "16", name: "Olexandr LARIONOV", team: "McLaren", time: "1:53.132", gap: "+7.025" },
                { pos: 11, number: "68", name: "Dmytro SHOLOPKO", team: "McLaren", time: "1:36.853", gap: "-9.254" },
                { pos: 12, number: "27", name: "Maksym MYKHLYK", team: "Ferrari", time: "1:37.154", gap: "-8.953" },
                { pos: 13, number: "13", name: "Bogdan VOSKOBIINYK", team: "Aston Martin", time: "1:41.165", gap: "-4.942" },
                { pos: 14, number: "55", name: "Illya KHUDAVSKYI", team: "Haas F1 Team", time: "--:--.----", gap: "--:--.----" },
                { pos: 15, number: "46", name: "Artem VODOPIANOV", team: "Haas F1 Team", time: "--:--.----", gap: "--:--.----" },
                { pos: 16, number: "91", name: "Oleh LIASHKO", team: "Ferrari", time: "--:--.----", gap: "--:--.----" },
                { pos: 17, number: "65", name: "Vladyslav POROSHENKO", team: "Williams", time: "--:--.----", gap: "--:--.----" },
            ],
            race: [
                { pos: 1, number: "85", name: "Yulian HULYK", team: "Aston Martin", time: "99:18.437", gap: "LEADER", points: 26 },
                { pos: 2, number: "06", name: "Olexandr KORZHOVSKYI", team: "Williams", time: "+9.253s", gap: "-", points: 18 },
                { pos: 3, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "+25.734s", gap: "-", points: 15 },
                { pos: 4, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "+26.379s", gap: "-", points: 12 },
                { pos: 5, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "+37.297s", gap: "-", points: 10 },
                { pos: 6, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "+58.501s", gap: "-", points: 8 },
                { pos: 7, number: "46", name: "Artem VODOPIANOV", team: "Haas F1 Team", time: "+1:16.845", gap: "-", points: 6 },
                { pos: 8, number: "55", name: "Illya KHUDAVSKYI", team: "Haas F1 Team", time: "+1 lap", gap: "-", points: 4 },
                { pos: 9, number: "27", name: "Maksym MYKHLYK", team: "Ferrari", time: "+1 lap", gap: "-", points: 2 },
                { pos: 10, number: "68", name: "Dmytro SHOLOPKO", team: "McLaren", time: "+2 lap", gap: "-", points: 1 },
                { pos: 11, number: "16", name: "Olexandr LARIONOV", team: "McLaren", time: "DNF", gap: "-", points: 0 },
                { pos: 12, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "DNF", gap: "-", points: 0 },
                { pos: 13, number: "91", name: "Oleh LIASHKO", team: "Ferrari", time: "DNF", gap: "-", points: 0 },
                { pos: 14, number: "14", name: "Bohdan VOSKOBIINYK", team: "Aston Martin", time: "DNF", gap: "-", points: 0 },
                { pos: 15, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "DNF", gap: "-", points: 0 },
                { pos: 16, number: "05", name: "Denys ILCHUK", team: "Kick Sauber", time: "DNF", gap: "-", points: 0 },
                { pos: 17, number: "65", name: "Vladyslav POROSHENKO", team: "Williams", time: "DSQ", gap: "-", points: 0 },
                { pos: 18, number: "64", name: "Denys ZABARNYI", team: "Racing Bulls", time: "DNS", gap: "-", points: 0 },
                { pos: 19, number: "32", name: "Dmytro POLIANSKYI", team: "Racing Bulls", time: "DNS", gap: "-", points: 0 },
          ]
        }
    },
    {
        round: 3,
        country: "Japan",
        sessions: {
            qualifying: [
                { pos: 1, number: "85", name: "Yulian HULYK", team: "Aston Martin", time: "1:26.878", gap: "LEADER" },
                { pos: 2, number: "10", name: "Yaroslav LOBODA", team: "Aston Martin", time: "1:27.787", gap: "+0.909" },
                { pos: 3, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "1:27.943", gap: "+1.065" },
                { pos: 4, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "1:27.960", gap: "+1.082" },
                { pos: 5, number: "82", name: "Hlib BRATUS", team: "Haas F1 Team", time: "1:28.645", gap: "+1.767" },
                { pos: 6, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "1:28.925", gap: "+2.047" },
                { pos: 7, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "1:29.017", gap: "+2.139" },
                { pos: 8, number: "18", name: "Mykhailo ILLIUK", team: "Williams", time: "1:29.150", gap: "+2.272" },
                { pos: 9, number: "29", name: "Nazar SHTEFANIUK", team: "Williams", time: "1:29.519", gap: "+2.641" },
                { pos: 10, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "1:29.575", gap: "+2.697" },
                { pos: 11, number: "59", name: "Rostyslav PYLIAK", team: "Ferrari", time: "1:30.815", gap: "+3.937" },
                { pos: 12, number: "68", name: "Dmytro SHOLOPKO", team: "Racing Bulls", time: "1:31.263", gap: "+4.385" },
                { pos: 13, number: "24", name: "Stanislav KRICHFALOVSKYI", team: "Kick Sauber", time: "1:32.831", gap: "+5.953" },
                { pos: 14, number: "27", name: "Maksym MYKHLYK", team: "Ferrari", time: "--:--.----", gap: "--:--.----" },
                { pos: 15, number: "16", name: "Olexandr Larionov", team: "McLaren", time: "--:--.----", gap: "--:--.----" },
            ],
            race: [
                { pos: 1, number: "65", name: "Vladyslav POROSHENKO", team: "McLaren", time: "94:19.637", gap: "LEADER", points: 26 },
                { pos: 2, number: "85", name: "Yulian HULYK", team: "Aston Martin", time: "+1.408s", gap: "-", points: 18 },
                { pos: 3, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "+11.989s", gap: "-", points: 15 },
                { pos: 4, number: "82", name: "Hlib BRATUS", team: "Alpine", time: "+14.483s", gap: "-", points: 12 },
                { pos: 5, number: "29", name: "Nazar SHTEFANIUK", team: "Williams", time: "+17.723s", gap: "-", points: 10 },
                { pos: 6, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "+22.442s", gap: "-", points: 8 },
                { pos: 7, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "+34.780s", gap: "-", points: 6 },
                { pos: 8, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "+39.145s", gap: "-", points: 4 },
                { pos: 9, number: "68", name: "Dmytro SHOLOPKO", team: "Racing Bulls", time: "+1 lap", gap: "-", points: 2 },
                { pos: 10, number: "27", name: "Maksym MYKHLYK", team: "Ferrari", time: "+1 lap", gap: "-", points: 1 },
                { pos: 11, number: "24", name: "Stanislav KRICHFALOVSKYI", team: "Kick Sauber", time: "+1 lap", gap: "-", points: 0 },
                { pos: 12, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "+2 laps", gap: "-", points: 0 },
                { pos: 13, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "DNF", gap: "-", points: 0 },
                { pos: 14, number: "18", name: "Mykhailo ILLIUK", team: "Williams", time: "DNF", gap: "-", points: 0 },
                { pos: 15, number: "59", name: "Rostyslav PYLIAK", team: "Ferrari", time: "DNF", gap: "-", points: 0 },
                { pos: 16, number: "16", name: "Olexandr Larionov", team: "McLaren", time: "DNS", gap: "-", points: 0 },
                { pos: 17, number: "06", name: "Olexandr KORZHOVSKYI", team: "Red Bull Racing", time: "DNS", gap: "-", points: 0 },
                { pos: 18, number: "03", name: "Maks ZHUK", team: "Aston Martin", time: "DNS", gap: "-", points: 0 },
            ]
        }
    },
    {
        round: 4,
        country: "Monaco",
        sessions: {
            qualifying: [
                 { pos: 1, number: "85", name: "Yulian HULYK", team: "Aston Martin", time: "1:09.740", gap: "LEADER" },
                 { pos: 2, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "1:10.006", gap: "+0.266" },
                 { pos: 3, number: "65", name: "Vladyslav POROSHENKO", team: "McLaren", time: "1:10.777", gap: "+1.037" },
                 { pos: 4, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "1:10.825", gap: "+1.085" },
                 { pos: 5, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "1:11.010", gap: "+1.270" },
                 { pos: 6, number: "18", name: "Mykhailo ILLIUK", team: "Williams", time: "1:11.820", gap: "+2.080" },
                 { pos: 7, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "1:12.089", gap: "+2.349" },
                 { pos: 8, number: "82", name: "Hlib BRATUS", team: "Haas F1 Team", time: "1:12.640", gap: "+2.900" },
                 { pos: 9, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "1:12.832", gap: "+3.092" },
                 { pos: 10, number: "24", name: "Stanislav KRICHFALOVSKYI", team: "Kick Sauber", time: "1:13.308", gap: "+3.568" },
                 { pos: 11, number: "59", name: "Rostyslav PYLIAK", team: "Ferrari", time: "1:14.520", gap: "+4.780" },
                 { pos: 12, number: "68", name: "Dmytro SHOLOPKO", team: "Racing Bulls", time: "1:15.274", gap: "+5.534" },
                 { pos: 13, number: "91", name: "Oleh LIASHKO", team: "McLaren", time: "1:24.381", gap: "+14.641" },
                 { pos: 14, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "--:--.----", gap: "--:--.----" },
                 { pos: 15, number: "29", name: "Nazar SHTEFANIUK", team: "Williams", time: "--:--.----", gap: "--:--.----" },
                 { pos: 16, number: "03", name: "Maks ZHUK", team: "Aston Martin", time: "--:--.----", gap: "--:--.----" },
                 { pos: 17, number: "27", name: "Maksym MYKHLYK", team: "Ferrari", time: "--:--.----", gap: "--:--.----" },
                 { pos: 18, number: "06", name: "Olexandr KORZHOVSKYI", team: "Red Bull Racing", time: "--:--.----", gap: "--:--.----" },
            
                ],
            race: [
                 { pos: 1, number: "85", name: "Yulian HULYK", team: "Aston Martin", time: "105:41.527", gap: "LEADER", points: 13 },
                 { pos: 2, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "+31.347", gap: "-", points: 9 },
                 { pos: 3, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "+1:19.365", gap: "-", points: 8 },
                 { pos: 4, number: "82", name: "Hlib BRATUS", team: "Haas F1 Team", time: "+1 lap", gap: "-", points: 7 },
                 { pos: 5, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "+1 lap", gap: "-", points: 6 },
                 { pos: 6, number: "18", name: "Mykhailo ILLIUK", team: "Williams", time: "+1 lap", gap: "-", points: 5 },
                 { pos: 7, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "DNF", gap: "-", points: 4 },
                 { pos: 8, number: "59", name: "Rostyslav PYLIAK", team: "Ferrari", time: "DNF", gap: "-", points: 3 },
                 { pos: 9, number: "68", name: "Dmytro SHOLOPKO", team: "Racing Bulls", time: "DNF", gap: "-", points: 2 },
                 { pos: 10, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "DNF", gap: "-", points: 1 },
                 { pos: 11, number: "24", name: "Stanislav KRICHFALOVSKYI", team: "Kick Sauber", time: "DNF", gap: "-", points: 0 },
                 { pos: 12, number: "91", name: "Oleh LIASHKO", team: "McLaren", time: "DNF", gap: "-", points: 0 },
                 { pos: 13, number: "65", name: "Vladyslav POROSHENKO", team: "McLaren", time: "DNF", gap: "-", points: 0 },
                 { pos: 14, number: "27", name: "Maksym MYKHLYK", team: "Ferrari", time: "DNS", gap: "-", points: 0 },
                 { pos: 15, number: "06", name: "Olexandr KORZHOVSKYI", team: "Red Bull Racing", time: "DNS", gap: "-", points: 0 },
                 { pos: 16, number: "03", name: "Maks ZHUK", team: "Aston Martin", time: "DNS", gap: "-", points: 0 },
                 { pos: 17, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "DNS", gap: "-", points: 0 },
                 { pos: 18, number: "29", name: "Nazar SHTEFANIUK", team: "Williams", time: "DNS", gap: "-", points: 0 },
]
        }
    },
    {
        round: 5,
        country: "Great Britain",
        sessions: {
            qualifying: [
               { pos: 1, number: "85", name: "Yulian HULYK", team: "Aston Martin", time: "1:25.746", gap: "LEADER" },
               { pos: 2, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "1:26.343", gap: "+0.597" },
               { pos: 3, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "1:26.635", gap: "+0.889" },
               { pos: 4, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "1:26.683", gap: "+0.937" },
               { pos: 5, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "1:27.314", gap: "+1.568" },
               { pos: 6, number: "87", name: "Stanislav MARCHENKO", team: "Haas F1 Team", time: "1:27.495", gap: "+1.749" },
               { pos: 7, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "1:27.746", gap: "+2.000" },
               { pos: 8, number: "18", name: "Mykhailo ILLIUK", team: "Williams", time: "1:27.846", gap: "+2.100" },
               { pos: 9, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "1:28.065", gap: "+2.319" },
               { pos: 10, number: "59", name: "Rostyslav PYLIAK", team: "Ferrari", time: "1:28.128", gap: "+2.382" },
               { pos: 11, number: "24", name: "Stanislav KRICHFALOVSKYI", team: "Kick Sauber", time: "1:29.512", gap: "+3.766" },
               { pos: 12, number: "68", name: "Dmytro SHOLOPKO", team: "Racing Bulls", time: "1:30.600", gap: "+4.854" },
               { pos: 13, number: "27", name: "Maksym MYKHLYK", team: "Ferrari", time: "1:30.765", gap: "+5.019" },
               { pos: 14, number: "91", name: "Oleh LIASHKO", team: "McLaren", time: "1:31.434", gap: "+5.688" },
               { pos: 15, number: "29", name: "Nazar SHTEFANIUK", team: "Williams", time: "--:--.----", gap: "--:--.----" },
               { pos: 16, number: "03", name: "Maks ZHUK", team: "Aston Martin", time: "--:--.----", gap: "--:--.----" },
               { pos: 17, number: "82", name: "Hlib BRATUS", team: "Haas F1 Team", time: "--:--.----", gap: "--:--.----" },
               { pos: 18, number: "06", name: "Hlib BRATUS", team: "Haas F1 Team", time: "--:--.----", gap: "--:--.----" },

            ],
            race: [ 
               { pos: 1, number: "85", name: "Yulian HULYK", team: "Aston Martin", time: "86:55.483", gap: "LEADER", points: 26 },
               { pos: 2, number: "40", name: "Volodymyr SHAKULA", team: "Kick Sauber", time: "+8.470", gap: "-", points: 18 },
               { pos: 3, number: "15", name: "Yaroslav PANKRATOV", team: "Alpine", time: "+12.285", gap: "-", points: 15 },
               { pos: 4, number: "22", name: "Yevhenii PANCHENKO", team: "Mercedes", time: "+15.171", gap: "-", points: 12 },
               { pos: 5, number: "59", name: "Rostyslav PYLIAK", team: "Ferrari", time: "+30.445", gap: "-", points: 10 },
               { pos: 6, number: "69", name: "Volodymyr MYKHALYUK", team: "Red Bull Racing", time: "+32.879", gap: "-", points: 8 },
               { pos: 7, number: "18", name: "Mykhailo ILLIUK", team: "Williams", time: "+35.678", gap: "-", points: 6 },
               { pos: 8, number: "52", name: "Maksym FILIPOV", team: "Mercedes", time: "+1 lap", gap: "-", points: 4 },
               { pos: 9, number: "68", name: "Dmytro SHOLOPKO", team: "Racing Bulls", time: "+1 lap", gap: "-", points: 2 },
               { pos: 10, number: "24", name: "Stanislav KRICHFALOVSKYI", team: "Kick Sauber", time: "+1 lap", gap: "-", points: 1 },
               { pos: 11, number: "27", name: "Maksym MYKHLYK", team: "Ferrari", time: "+1 lap", gap: "-", points: 0 },
               { pos: 12, number: "87", name: "Stanislav MARCHENKO", team: "Haas F1 Team", time: "DNF", gap: "-", points: 0 },
               { pos: 13, number: "91", name: "Oleh LIASHKO", team: "McLaren", time: "DNF", gap: "-", points: 0 },
               { pos: 14, number: "10", name: "Yaroslav LOBODA", team: "Alpine", time: "DNF", gap: "-", points: 0 },
               { pos: 15, number: "06", name: "Olexandr KORZHOVSKYI", team: "Red Bull Racing", time: "DNS", gap: "-", points: 0 },
               { pos: 16, number: "03", name: "Maks ZHUK", team: "Aston Martin", time: "DNS", gap: "-", points: 0 },
               { pos: 17, number: "29", name: "Nazar SHTEFANIUK", team: "Williams", time: "DNS", gap: "-", points: 0 },
               { pos: 18, number: "82", name: "Hlib BRATUS", team: "Haas F1 Team", time: "DNS", gap: "-", points: 0 },
            ]
        }
    }
];